/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.crowd.funding.database.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FundReleaseRegistration service. Represents a row in the &quot;cf_fund_release_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.crowd.funding.database.model.impl.FundReleaseRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.crowd.funding.database.model.impl.FundReleaseRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FundReleaseRegistration
 * @see com.crowd.funding.database.model.impl.FundReleaseRegistrationImpl
 * @see com.crowd.funding.database.model.impl.FundReleaseRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface FundReleaseRegistrationModel extends BaseModel<FundReleaseRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fund release registration model instance should use the {@link FundReleaseRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this fund release registration.
	 *
	 * @return the primary key of this fund release registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fund release registration.
	 *
	 * @param primaryKey the primary key of this fund release registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fund release registration.
	 *
	 * @return the uuid of this fund release registration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this fund release registration.
	 *
	 * @param uuid the uuid of this fund release registration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the fund_release_id of this fund release registration.
	 *
	 * @return the fund_release_id of this fund release registration
	 */
	public long getFUND_RELEASE_ID();

	/**
	 * Sets the fund_release_id of this fund release registration.
	 *
	 * @param FUND_RELEASE_ID the fund_release_id of this fund release registration
	 */
	public void setFUND_RELEASE_ID(long FUND_RELEASE_ID);

	/**
	 * Returns the project_id of this fund release registration.
	 *
	 * @return the project_id of this fund release registration
	 */
	public long getPROJECT_ID();

	/**
	 * Sets the project_id of this fund release registration.
	 *
	 * @param PROJECT_ID the project_id of this fund release registration
	 */
	public void setPROJECT_ID(long PROJECT_ID);

	/**
	 * Returns the currency of this fund release registration.
	 *
	 * @return the currency of this fund release registration
	 */
	@AutoEscape
	public String getCURRENCY();

	/**
	 * Sets the currency of this fund release registration.
	 *
	 * @param CURRENCY the currency of this fund release registration
	 */
	public void setCURRENCY(String CURRENCY);

	/**
	 * Returns the amount of this fund release registration.
	 *
	 * @return the amount of this fund release registration
	 */
	public float getAMOUNT();

	/**
	 * Sets the amount of this fund release registration.
	 *
	 * @param AMOUNT the amount of this fund release registration
	 */
	public void setAMOUNT(float AMOUNT);

	/**
	 * Returns the release_date of this fund release registration.
	 *
	 * @return the release_date of this fund release registration
	 */
	public Date getRELEASE_DATE();

	/**
	 * Sets the release_date of this fund release registration.
	 *
	 * @param RELEASE_DATE the release_date of this fund release registration
	 */
	public void setRELEASE_DATE(Date RELEASE_DATE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FundReleaseRegistration fundReleaseRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FundReleaseRegistration> toCacheModel();

	@Override
	public FundReleaseRegistration toEscapedModel();

	@Override
	public FundReleaseRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}